services:

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    hostname: grafana
    image: grafana/grafana
    ports:
      - 3000:3000

  app:
    build: .
    depends_on:
      - prometheus
    ports:
      - 9000:9000
      - 8000:8000
    command: ["python3", "./server.py"]